title:        Screen Capture API
url:          http://kin-lane.github.io/screen-capture/
version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true

permalink: /:categories/:year/:month/:day/:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 50
paginate_path: "/news/page:num"

production_url : http://kin-lane.github.io/screen-capture/

BASE_PATH : http://kin-lane.github.io/screen-capture/

categories_path : /categories.html
tags_path : /tags.html

org: Kin-Lane
repo: screen-capture
resource: Screen-Capture
oauthio: qUDL4eZqKPFb41SwuWIYIwLR6jI
